### ISSUE TITLE
GPU version of BiWFA

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [quim0/WFA-GPU#1]
Hey!

It's quite possible you are already working on this, but anyway, a GPU version of BiWFA may solve some of the issues you are having:
- lower memory consumption, so it can scale to larger error rates
- you could recurse into blocks with known edit distance, e.g. exactly a power of 2, which should allow for efficient allocating of threads
- the left and right recursion at each level are independent, so this should parallelize nicely. (Although the top-level will still be a bottleneck of course.)

Another thing that _may_ be useful (probably not though) is to do exponential search on the edit distance. That way, you can double the allocated resources in steps and fall back to the E64 kernel once the E32 kernel determines the distances is > 32, and then fall back to E128 once the E64 kernel reports a distance > 64.

**Comment by smarco** [comment]
Hi, Ragnar.

Yes, indeed. We have been working towards BiWFA GPU. As you point out, it solves many of the problems Quim's WFA-GPU implementation endures. The memory footprint reduction is one of the main advantages. Also, after the first breakpoint, we know the remaining alignments/recursion score. We have been exploring the idea of specialized kernels and how to optimize the number of blocks/threads devoted to each alignment. I'll happily follow up on this conversation and discuss these ideas by email if you want.

Cheers,
