### ISSUE TITLE
Citations of Ukkonen'85 and Myers'86

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [quim0/WFA-GPU#2]
I'm sorry for being so pedantic about this and repeatedly making this point, but especially since this paper only computes edit distance (and not linear/affine costs), I'm raising it again:

**Ukkonen'85: Algorithms for approximate string matching [52]**

You implement the algorithm of Ukkonen'85. You _do_ cite this paper, but only for the property that diagonals are monotonically increasing.

To be specific:
- Equation (8), line 1. of Ukkonen has the same recursion as your Algorithm 2 (`computeNext`)
- Equation (8), line 2. of Ukkonen corresponds to your Algorithm 1 (`extend`). 
- Equations (10) and (11) of Ukkonen correspond to you Algorithm 3.

The only real difference is that you split the `computeNext` and `extend` steps, while Ukkonen merges them.

**Myers'86: An $O(ND)$ difference algorithm and its variations [45]**

This paper basically proposes the same algorithm as Ukkonen'85, but with one modification:
- it computes LCS instead of edit distance
in particular, this means that substitutions are not allowed, which introduces a parity between odd/even fronts and diagonals.

Otherwise, figure 2 of Myers corresponds to your code:
- line 4..7 are `computeNext`
- line 8..10 is `extend`
- line 11..13 is the stop condition, which seems to be slightly different

For completeness, I'll note that section 4.2 of Myers applies the idea of Hirschberg'75 (divide&conquer), which is similar to BiWFA.

You cite this paper 4 times:
- The first time you cite it for bit-packed encodings, alongside Myers'99. I don't see what Myers'86 has to do with bit packing.
- The 2nd citation is because `Daligner` implements this.
- The 3rd citation is because you compare to it.
- The 4th citation is for related work.

None of these states that you implement a generalization of this algorithm.

CC @smarco @ekg

**Comment by quim0** [comment]
Same as #3
